#
# This is a sample configuration file for the ngIRCd IRC daemon, which must
# be customized to the local preferences and needs.
#
# Comments are started with "#" or ";".
#
# A lot of configuration options in this file start with a ";". You have
# to remove the ";" in front of each variable to actually set a value!
# The disabled variables are shown with example values for completeness only
# and the daemon is using compiled-in default settings.
#
# Use "ngircd --configtest" (see manual page ngircd(8)) to validate that the
# server interprets the configuration file as expected!
#
# Please see ngircd.conf(5) for a complete list of configuration options
# and their descriptions.
#
[Global]
	;Name = irc.example.net
	;AdminInfo1 = Description
	;AdminInfo2 = Location
	;AdminEMail = admin@irc.server
	;HelpFile = /usr/share/doc/ngircd/Commands.txt
	;Info = Server Info Text
	;Listen = 127.0.0.1,192.168.0.1
	;MotdFile = /etc/ngircd/ngircd.motd
	;MotdPhrase = "Hello world!"
	;Network = aIRCnetwork
	;Password = abc
	;PidFile = /var/run/ngircd/ngircd.pid
	;Ports = 6667, 6668, 6669
	;ServerGID = 65534
	;ServerUID = 65534
[Limits]
	;ConnectRetry = 60
	;IdleTimeout = 0
	;MaxConnections = 0
	;MaxConnectionsIP = 5
	;MaxJoins = 10
	;MaxNickLength = 9
	;MaxPenaltyTime = -1
	;MaxListSize = 100
	;PingTimeout = 120
	;PongTimeout = 20
[Options]
	;AllowedChannelTypes = #&+
	;AllowRemoteOper = no
	;ChrootDir = /var/empty
	;CloakHost = cloaked.host
	;CloakHostModeX = cloaked.user
	;CloakHostSalt = abcdefghijklmnopqrstuvwxyz
	;CloakUserToNick = yes
	;ConnectIPv6 = yes
	;ConnectIPv4 = yes
	;DefaultUserModes = i
	;DNS = yes
	;Ident = yes
	;IncludeDir = /etc/ngircd/conf.d
	;MorePrivacy = no
	;NoticeBeforeRegistration = no
	;OperCanUseMode = no
	;OperChanPAutoOp = yes
	;OperServerMode = no
	;PAM = yes
	;PAMIsOptional = no
	;PAMServiceName = ngircd
	;RequireAuthPing = no
	;ScrubCTCP = no
	;SyslogFacility = local1
	;WebircPassword = xyz
;[SSL]
	;CAFile = /etc/ssl/CA/cacert.pem
	;CRLFile = /etc/ssl/CA/crl.pem
	;CertFile = /etc/ngircd/ssl/server-cert.pem
	;CipherList = HIGH:!aNULL:@STRENGTH:!SSLv3
	;CipherList = SECURE128:-VERS-SSL3.0
	;DHFile = /etc/ngircd/ssl/dhparams.pem
	;KeyFile = /etc/ngircd/ssl/server-key.pem
	;KeyFilePassword = secret
	;Ports = 6697, 9999
[Operator]
	;Name = TheOper
	;Password = ThePwd
	;Mask = *!ident@somewhere.example.com
[Operator]
[Server]
	;Name = irc2.example.net
	;Host = connect-to-host.example.net
	;Bind = 10.0.0.1
	;Port = 6667
	;MyPassword = MySecret
	;PeerPassword = PeerSecret
	;Group = 123
	;Passive = no
	;SSLConnect = yes
	;SSLVerify = yes
	;ServiceMask = *Serv,Global
[Server]
[Channel]
	;Name = #TheName
	;Topic = a great topic
	;Modes = +tnk mykey +l 5
	;Modes = +b nick!~user@bad.host.example.com
	;Autojoin = yes
	;KeyFile = /etc/ngircd/#chan.key
[Channel]
# -eof-
